-- MySQL Script generated by MySQL Workbench
-- Thu Nov 15 16:28:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema perenoel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `perenoel` ;

-- -----------------------------------------------------
-- Schema perenoel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `perenoel` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `perenoel` ;

-- -----------------------------------------------------
-- Table `perenoel`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perenoel`.`users` ;

CREATE TABLE IF NOT EXISTS `perenoel`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nom` VARCHAR(64) NULL COMMENT '',
  `prenom` VARCHAR(64) NULL COMMENT '',
  `email` VARCHAR(64) NULL COMMENT '',
  `password` VARCHAR(512) NULL COMMENT '',
  PRIMARY KEY (`idusers`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perenoel`.`evenements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perenoel`.`evenements` ;

CREATE TABLE IF NOT EXISTS `perenoel`.`evenements` (
  `idevenements` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nomevenement` VARCHAR(64) NULL COMMENT '',
  `id_user` INT NULL COMMENT '',
  INDEX `fk_evt_users_idx` (`id_user` ASC)  COMMENT '',
  PRIMARY KEY (`idevenements`)  COMMENT '',
  CONSTRAINT `fk_evt_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `perenoel`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perenoel`.`invites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perenoel`.`invites` ;

CREATE TABLE IF NOT EXISTS `perenoel`.`invites` (
  `idinvites` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `pseudo` VARCHAR(64) NULL COMMENT '',
  `email` VARCHAR(64) NULL COMMENT '',
  `idevenement` INT NULL COMMENT '',
  PRIMARY KEY (`idinvites`)  COMMENT '',
  INDEX `fk_invit_evt_idx` (`idevenement` ASC)  COMMENT '',
  CONSTRAINT `fk_invit_evt`
    FOREIGN KEY (`idevenement`)
    REFERENCES `perenoel`.`evenements` (`idevenements`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

